"""initial_schema

Revision ID: 719d6c7f3de2
Revises: 
Create Date: 2026-05-29 23:50:01.694972
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import app.models.types

# revision identifiers, used by Alembic.
revision: str = '719d6c7f3de2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_practice_created', 'audit_logs', ['practice_id', 'created_at'], unique=False)
    op.create_table('practices',
    sa.Column('clerk_org_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), server_default='America/New_York', nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=True),
    sa.Column('pms_system', sa.Text(), nullable=False),
    sa.Column('pms_credentials_secret_key', sa.Text(), nullable=True),
    sa.Column('languages_enabled', sa.ARRAY(sa.Text()), server_default='{en}', nullable=False),
    sa.Column('business_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retell_agent_id', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_org_id')
    )
    op.create_table('patients',
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('pms_external_id', sa.Text(), nullable=False),
    sa.Column('first_name', app.models.types.EncryptedString(), nullable=True),
    sa.Column('last_name', app.models.types.EncryptedString(), nullable=True),
    sa.Column('phone', app.models.types.EncryptedString(), nullable=True),
    sa.Column('email', app.models.types.EncryptedString(), nullable=True),
    sa.Column('date_of_birth', app.models.types.EncryptedString(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('practice_id', 'pms_external_id', name='uq_patient_practice_pms')
    )
    op.create_table('users',
    sa.Column('clerk_user_id', sa.Text(), nullable=False),
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_user_id')
    )
    op.create_table('calls',
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('retell_call_id', sa.Text(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('from_number', sa.Text(), nullable=False),
    sa.Column('to_number', sa.Text(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('recording_path', sa.Text(), nullable=True),
    sa.Column('transcript_jsonb', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('language_detected', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retell_call_id')
    )
    op.create_index('ix_calls_practice_started', 'calls', ['practice_id', 'started_at'], unique=False)
    op.create_table('bookings',
    sa.Column('practice_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('source_call_id', sa.UUID(), nullable=True),
    sa.Column('pms_external_id', sa.Text(), nullable=True),
    sa.Column('appointment_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), server_default='60', nullable=False),
    sa.Column('procedure_type', sa.Text(), nullable=True),
    sa.Column('provider_name', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='confirmed', nullable=False),
    sa.Column('source', sa.Text(), server_default='ai_call', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ),
    sa.ForeignKeyConstraint(['source_call_id'], ['calls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookings_practice_appt', 'bookings', ['practice_id', 'appointment_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookings_practice_appt', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_calls_practice_started', table_name='calls')
    op.drop_table('calls')
    op.drop_table('users')
    op.drop_table('patients')
    op.drop_table('practices')
    op.drop_index('ix_audit_practice_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
